let shopItemsData = [
    {
        id: "special",
        name: "Dress",
        price: 1750,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "Assets/img/dress/dress1.webp",
    },
    {
        id: "special1",
        name: "Dress1",
        price: 1734,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "Assets/img/dress/dress2.webp",
    },
    {
        id: "special2",
        name: "Dress2",
        price: 1746,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "Assets/img/dress/dress3.webp",
    },
    {
        id: "special3",
        name: "Dress3",
        price: 1726,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "Assets/img/dress/dress4.webp",
    },
    {
        id: "special4",
        name: "repeatDress",
        price: 1234,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "Assets/img/dress/dress1.webp",
    },
    {
        id: "special5",
        name: "repeatDress1",
        price: 1465,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "Assets/img/dress/dress2.webp",
    },
    {
        id: "special6",
        name: "repeatDress2",
        price: 1789,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "Assets/img/dress/dress3.webp",
    },
    {
        id: "special7",
        name: "repeatDress3",
        price: 1456,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "Assets/img/dress/dress4.webp",
    },
    {
        id: "special8",
        name: "RepeatDress",
        price: 1397,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "Assets/img/dress/dress1.webp",
    },
    {
        id: "special9",
        name: "RepeatDress1",
        price: 1207,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "Assets/img/dress/dress2.webp",
    },
    {
        id: "special10",
        name: "RepeatDress2",
        price: 1300,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "Assets/img/dress/dress3.webp",
    },
    {
        id: "special11",
        name: "RepeatDress3",
        price: 1867,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "Assets/img/dress/dress4.webp",
    },


];