let shopItemsData = [
    {
        id: "pants",
        name: "AwesomePants",
        price: 45,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "Assets/img/Pants/Pants.png",
    },
    {
        id: "pants1",
        name: "AwesomePants1",
        price: 3645,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "Assets/img/Pants/pants1.png",
    },
    {
        id: "pants2",
        name: "AwesomePants2",
        price: 5867,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "Assets/img/Pants/pants2.png",
    },
    {
        id: "pants3",
        name: "AwesomePants3",
        price: 1234,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "Assets/img/Pants/pants3.png",
    },
    {
        id: "pants4",
        name: "AwesomePants4",
        price:5678,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "Assets/img/Pants/pants4.png",
    },
    {
        id: "pants5",
        name: "AwesomePants5",
        price: 6845,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "Assets/img/Pants/pants5.png",
    },
    {
        id: "pants6",
        name: "AwesomePants6",
        price: 6873,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "Assets/img/Pants/pants6.png",
    },
    {
        id: "pants7",
        name: "AwesomePants7",
        price: 4534,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "Assets/img/Pants/pants7.png",
    },
    {
        id: "pants8",
        name: "AwesomePants8",
        price: 6873,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "Assets/img/Pants/pants8.png",
    },
    {
        id: "pants9",
        name: "AwesomePants9",
        price: 3427,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "Assets/img/Pants/pants9.png",
    },
    {
        id: "pants10",
        name: "AwesomePants10",
        price: 8670,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "Assets/img/Pants/pants10.png",
    },
    {
        id: "pants11",
        name: "AwesomePants11",
        price: 8195,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "Assets/img/Pants/pants11.png",
    },

];