let shopItemsData = [
    {
        id: "3.141",
        name: "shirt",
        price: 45,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "Assets/img/ProdFeat/Products1.png",
    },
    {
        id: "3.1415",
        name: "white shirt",
        price: 3645,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "Assets/img/ProdFeat/Products2.png",
    },
    {
        id: "3.14159",
        name: "black shirt",
        price: 5867,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "Assets/img/ProdFeat/Products3.png",
    },
    {
        id: "3.141592",
        name: "serene",
        price: 1234,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "Assets/img/ProdFeat/Products4.png",
    },
    {
        id: "3.1415926",
        name: "white pants",
        price:5678,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "Assets/img/ProdFeat/Products5.png",
    },
    {
        id: "3.14159265",
        name: "shirtdress",
        price: 6845,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "Assets/img/ProdFeat/Products6.png",
    },
    {
        id: "3.141592653",
        name: "skirt",
        price: 6873,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "Assets/img/ProdFeat/Products7.png",
    },
    {
        id: "3.1415926536",
        name: "ripped jeans",
        price: 4534,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "Assets/img/ProdFeat/Products8.png",
    },
    {
        id: "3.14159265359",
        name: "black dress",
        price: 6873,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "Assets/img/ProdFeat/Products9.png",
    },
    {
        id: "3.141592653589",
        name: "other black dress",
        price: 3427,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "Assets/img/ProdFeat/Products10.png",
    },
    {
        id: "3.1415926535897",
        name: "Capslock N",
        price: 8670,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "Assets/img/ProdFeat/Products11.png",
    },
    {
        id: "3.14159265358979",
        name: "Hoodie",
        price: 8195,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "Assets/img/ProdFeat/Products12.png",
    },

];