let shopItemsData = [
    {
        id: "bag1",
        name: "awesomebag1",
        price: 45,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "Assets/img/bags/bag1.png",
    },
    {
        id: "bag2",
        name: "awesomebag2",
        price: 3645,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "Assets/img/bags/bag2.png",
    },
    {
        id: "bag3",
        name: "awesomebag3",
        price: 5867,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "Assets/img/bags/bag3.png",
    },
    {
        id: "bag4",
        name: "awesomebag4",
        price: 1234,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "Assets/img/bags/bag4.png",
    },
    {
        id: "bag5",
        name: "awesomebag5",
        price:5678,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "Assets/img/bags/bag5.png",
    },
    {
        id: "bag6",
        name: "awesomebag6",
        price: 6845,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "Assets/img/bags/bag6.png",
    },
    {
        id: "bag7",
        name: "awesomebag7",
        price: 6873,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "Assets/img/bags/bag7.png",
    },
    {
        id: "bag8",
        name: "awesomebag8",
        price: 4534,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "Assets/img/bags/bag8.png",
    },
    {
        id: "bag9",
        name: "awesomebag9",
        price: 6873,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "Assets/img/bags/bag9.png",
    },
    {
        id: "bag10",
        name: "awesomebag10",
        price: 3427,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "Assets/img/bags/bag10.png",
    },
    {
        id: "bag11",
        name: "awesomebag11",
        price: 8670,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "Assets/img/bags/bag11.png",
    },
    {
        id: "bag12",
        name: "awesomebag12",
        price: 8195,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "Assets/img/bags/bag12.png",
    },

];